apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ template "weatherapp.fullname" . }}
  namespace: default
spec:
  hosts:
  - {{ .Values.gatewayhostname }}
  gateways:
  - {{ template "weatherapp.fullname" . }}
  http:
  - route:
    - destination:
        host:  {{ template "weatherapp.fullname" . }}
 